name       : routino
version    : 3.2
release    : 1
source     :
    - https://www.routino.org/download/routino-3.2.tgz : e2a431eaffbafab630835966d342e4ae25d5edb94c8ed419200e1ffb50bc7552
license    : AGPL-3.0-or-later
component  : system.utils
summary    : Routino is an application for finding a route between two points
description: |
    Routino is a command-line application for finding a route between two points using the dataset of topographical information collected by OpenStreetMap.
builddeps  :
    - bzip2-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-paths.patch
build      : |
    %make
install    : |
    %make_install libdir=%libdir%
check      : |
    %make test
